#!/bin/bash
# This file was generated by Bin_Splitter.C
# ** source this file while in this directory

export SPINDIR=$(pwd)

export PHI_LOW=-3.150000
export PHI_HIGH=3.150000
export PHI_BINS=10
export PHI_DIV_0=-3.150000
export PHI_DIV_1=-2.520000
export PHI_DIV_2=-1.890000
export PHI_DIV_3=-1.260000
export PHI_DIV_4=-0.630000
export PHI_DIV_5=0.000000
export PHI_DIV_6=0.630000
export PHI_DIV_7=1.260000
export PHI_DIV_8=1.890000
export PHI_DIV_9=2.520000
export PHI_DIV_10=3.150000

export ETA_LOW=3.100000
export ETA_HIGH=3.900000
export ETA_BINS=1
export ETA_DIV_0=3.100000
export ETA_DIV_1=3.900000

export PT_LOW=2.000000
export PT_HIGH=10.000000
export PT_BINS=4
export PT_DIV_0=2.000000
export PT_DIV_1=3.400000
export PT_DIV_2=4.400000
export PT_DIV_3=5.300000
export PT_DIV_4=10.000000

export EN_LOW=30.000000
export EN_HIGH=100.000000
export EN_BINS=1
export EN_DIV_0=30.000000
export EN_DIV_1=100.000000

export TRIGGER_TYPE="All"
export MASS_CUT_TYPE="en"
export RP_SELECT="N"

export STG1=2
export STG2=1
export MIPN=0
export USE_TCU_BITS=0
